In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
da1=pd.read_csv("./icr-identify-age-related-conditions/train.csv")

In [3]:
da1

,Id,AB,AF,AH,AM,AR,AX,AY,AZ,BC,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,Class
0,000ff2bfdfe9,0.209377,3109.03329,85.200147,22.394407,8.138688,0.699861,0.025578,9.812214,5.555634,...,7.298162,1.73855,0.094822,11.339138,72.611063,2003.810319,22.136229,69.834944,0.120343,1
1,007255e47698,0.145282,978.76416,85.200147,36.968889,8.138688,3.632190,0.025578,13.517790,1.229900,...,0.173229,0.49706,0.568932,9.292698,72.611063,27981.562750,29.135430,32.131996,21.978000,0
2,013f2bd269f5,0.470030,2635.10654,85.200147,32.360553,8.138688,6.732840,0.025578,12.824570,1.229900,...,7.709560,0.97556,1.198821,37.077772,88.609437,13676.957810,28.022851,35.192676,0.196941,0
3,043ac50845d5,0.252107,3819.65177,120.201618,77.112203,8.138688,3.685344,0.025578,11.053708,1.229900,...,6.122162,0.49706,0.284466,18.529584,82.416803,2094.262452,39.948656,90.493248,0.155829,0
4,044fb8a146ec,0.380297,3733.04844,85.200147,14.103738,8.138688,3.942255,0.054810,3.396778,102.151980,...,8.153058,48.50134,0.121914,16.408728,146.109943,8524.370502,45.381316,36.262628,0.096614,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,fd3dafe738fd,0.149555,3130.05946,123.763599,9.513984,13.020852,3.499305,0.077343,8.545512,2.804172,...,0.173229,1.26092,0.067730,8.967128,217.148554,8095.932828,24.640462,69.191944,21.978000,0
613,fd895603f071,0.435846,5462.03438,85.200147,46.551007,15.973224,5.979825,0.025882,12.622906,3.777550,...,10.223150,1.24236,0.426699,35.896418,496.994214,3085.308063,29.648928,124.808872,0.145340,0
614,fd8ef6377f76,0.427300,2459.10720,130.138587,55.355778,10.005552,8.070549,0.025578,15.408390,1.229900,...,0.173229,0.49706,0.067730,19.962092,128.896894,6474.652866,26.166072,119.559420,21.978000,0
615,fe1942975e40,0.363205,1263.53524,85.200147,23.685856,8.138688,7.981959,0.025578,7.524588,1.229900,...,9.256996,0.78764,0.670527,24.594488,72.611063,1965.343176,25.116750,37.155112,0.184622,0
616,ffcca4ded3bb,0.482849,2672.53426,546.663930,112.006102,8.138688,3.198099,0.116928,3.396778,7.948668,...,0.173229,1.14492,0.149006,13.673940,72.611063,6850.484442,45.745974,114.842372,21.978000,0

In [4]:
da_no1=da1[da1["Class"]==1]
da_no0=da1[da1["Class"]==0]

In [47]:
da_no1.to_csv("./icr-identify-age-related-conditions/da_no1.csv")

da_no0.to_csv("./icr-identify-age-related-conditions/sample_data/da_no1_2.numbers")

In [48]:
da_no0.describe()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,Class
count,509.000000,509.000000,509.000000,509.000000,509.000000,509.000000,509.000000,509.000000,509.000000,509.000000,...,508.000000,509.000000,508.000000,509.000000,509.000000,509.000000,509.000000,509.000000,508.000000,509.0
mean,0.416655,3181.597632,115.997626,31.292888,9.816552,5.430932,0.044508,10.539383,3.377568,5194.386843,...,4.139887,1.129568,0.420819,20.341573,136.411031,15821.588253,31.337443,49.300945,9.098095,0.0
std,0.325706,1677.157950,123.507052,39.542608,11.068698,2.107305,0.050073,4.297309,4.484045,1497.148292,...,9.217830,0.558116,1.420333,8.541468,152.953583,19932.516693,9.328552,35.335901,10.398146,0.0
min,0.081187,192.593280,85.200147,3.177522,8.138688,0.699861,0.025578,3.396778,1.229900,1693.624320,...,0.173229,0.497060,0.067730,4.102182,72.611063,13.038894,9.432735,0.897628,0.007333,0.0
25%,0.239288,2072.223010,85.200147,11.957517,8.138688,4.101717,0.025578,8.072862,1.229900,4183.564000,...,0.173229,0.497060,0.067730,13.906490,72.611063,3086.887077,25.060935,22.152636,0.159008,0.0
50%,0.333294,2919.819540,85.200147,19.405802,8.138688,4.996476,0.025578,10.341582,1.229900,5040.779140,...,2.463620,1.123460,0.250601,18.817946,72.611063,8095.932828,30.742902,40.393260,0.435421,0.0
75%,0.499941,4059.436260,114.923964,35.757962,8.138688,6.422775,0.039585,12.969516,4.469808,6035.885700,...,5.333832,1.477550,0.521521,25.515386,132.099219,21818.071870,36.808132,66.949160,21.978000,0.0
max,4.277273,14503.256020,1910.123198,630.518230,178.943634,17.877462,0.601997,38.971568,54.150740,12083.348910,...,110.342316,4.209350,31.365763,62.667574,1497.351958,143790.071200,80.537324,191.194764,21.978000,0.0

In [49]:
da_no1.describe()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,Class
count,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,...,108.000000,108.000000,107.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.000000,108.0
mean,0.762256,5012.120024,131.004931,75.143672,11.597227,6.085887,0.134840,10.693998,30.088202,6085.619418,...,11.516557,14.865456,0.424737,22.531253,109.582703,9297.425370,32.207374,56.633487,5.863328,1.0
std,0.812348,3783.979443,146.551293,137.717327,7.258732,4.005553,0.990708,4.612481,154.139328,6422.563218,...,17.655941,119.745058,0.470323,14.980096,89.490518,15313.372555,12.099369,39.987869,9.588968,0.0
min,0.132463,192.593280,85.200147,6.073217,8.138688,0.699861,0.025578,3.396778,1.229900,2141.759450,...,0.173229,0.497060,0.067730,5.878864,72.611063,13.038894,11.069975,3.914584,0.001129,1.0
25%,0.362137,3027.833820,85.200147,15.807862,8.138688,4.301044,0.025578,8.584900,1.229900,4053.560707,...,0.173229,0.687445,0.067730,14.572746,72.611063,1689.997689,24.752092,27.323963,0.055100,1.0
50%,0.557627,4088.147140,85.200147,30.463641,8.138688,5.346407,0.025578,11.151389,4.306407,4915.835515,...,7.248373,1.431150,0.257374,18.706322,72.611063,4878.427176,29.561484,43.225675,0.107237,1.0
75%,0.746707,5886.149967,100.031574,48.934923,11.437819,6.788209,0.028699,12.926977,8.405488,6003.076762,...,13.240362,1.854695,0.606183,25.946766,105.473543,11782.964420,37.307676,73.710626,21.978000,1.0
max,6.161666,28688.187660,1237.940805,630.518230,50.253252,38.270880,10.315851,30.192882,1463.693448,53060.599240,...,137.932739,1244.227020,2.614378,135.781294,771.058022,134409.538300,81.210825,176.662964,21.978000,1.0

#

In [50]:
da1.describe()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,Class
count,617.000000,617.000000,617.000000,617.000000,617.000000,617.000000,617.000000,617.000000,617.000000,617.000000,...,616.000000,617.000000,615.000000,617.000000,617.000000,617.000000,617.000000,617.000000,616.000000,617.000000
mean,0.477149,3502.013221,118.624513,38.968552,10.128242,5.545576,0.060320,10.566447,8.053012,5350.388655,...,5.433199,3.533905,0.421501,20.724856,131.714987,14679.595398,31.489716,50.584437,8.530961,0.175041
std,0.468388,2300.322717,127.838950,69.728226,10.518877,2.551696,0.416817,4.350645,65.166943,3021.326641,...,11.496257,50.181948,1.305365,9.991907,144.181524,19352.959387,9.864239,36.266251,10.327010,0.380310
min,0.081187,192.593280,85.200147,3.177522,8.138688,0.699861,0.025578,3.396778,1.229900,1693.624320,...,0.173229,0.497060,0.067730,4.102182,72.611063,13.038894,9.432735,0.897628,0.001129,0.000000
25%,0.252107,2197.345480,85.200147,12.270314,8.138688,4.128294,0.025578,8.129580,1.229900,4155.702870,...,0.173229,0.497060,0.067730,14.036718,72.611063,2798.992584,25.034888,23.011684,0.124392,0.000000
50%,0.354659,3120.318960,85.200147,20.533110,8.138688,5.031912,0.025578,10.461320,1.229900,4997.960730,...,3.028141,1.131000,0.250601,18.771436,72.611063,7838.273610,30.608946,41.007968,0.337827,0.000000
75%,0.559763,4361.637390,113.739540,39.139886,8.138688,6.431634,0.036845,12.969516,5.081244,6035.885700,...,6.238814,1.512060,0.535067,25.608406,127.591671,19035.709240,36.863947,67.931664,21.978000,0.000000
max,6.161666,28688.187660,1910.123198,630.518230,178.943634,38.270880,10.315851,38.971568,1463.693448,53060.599240,...,137.932739,1244.227020,31.365763,135.781294,1497.351958,143790.071200,81.210825,191.194764,21.978000,1.000000

In [51]:
da_no1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108 entries, 0 to 608
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      108 non-null    object
 1   AB      108 non-null    float64
 2   AF      108 non-null    float64
 3   AH      108 non-null    float64
 4   AM      108 non-null    float64
 5   AR      108 non-null    float64
 6   AX      108 non-null    float64
 7   AY      108 non-null    float64
 8   AZ      108 non-null    float64
 9   BC      108 non-null    float64
 10  BD      108 non-null    float64
 11  BN      108 non-null    float64
 12  BP      108 non-null    float64
 13  BQ      108 non-null    float64
 14  BR      108 non-null    float64
 15  BZ      108 non-null    float64
 16  CB      108 non-null    float64
 17  CC      107 non-null    float64
 18  CD      108 non-null    float64
 19  CF      108 non-null    float64
 20  CH      108 non-null    float64
 21  CL      108 non-null    float64
 22  CR      108 non-null    float64
 23  CS      108 non-null    float64
 24  CU      108 non-null    float64
 25  CW      108 non-null    float64
 26  DA      108 non-null    float64
 27  DE      108 non-null    float64
 28  DF      108 non-null    float64
 29  DH      108 non-null    float64
 30  DI      108 non-null    float64
 31  DL      108 non-null    float64
 32  DN      108 non-null    float64
 33  DU      108 non-null    float64
 34  DV      108 non-null    float64
 35  DY      108 non-null    float64
 36  EB      108 non-null    float64
 37  EE      108 non-null    float64
 38  EG      108 non-null    float64
 39  EH      108 non-null    float64
 40  EJ      108 non-null    object
 41  EL      102 non-null    float64
 42  EP      108 non-null    float64
 43  EU      108 non-null    float64
 44  FC      107 non-null    float64
 45  FD      108 non-null    float64
 46  FE      108 non-null    float64
 47  FI      108 non-null    float64
 48  FL      108 non-null    float64
 49  FR      108 non-null    float64
 50  FS      107 non-null    float64
 51  GB      108 non-null    float64
 52  GE      108 non-null    float64
 53  GF      108 non-null    float64
 54  GH      108 non-null    float64
 55  GI      108 non-null    float64
 56  GL      108 non-null    float64
 57  Class   108 non-null    int64
dtypes: float64(55), int64(1), object(2)
memory usage: 49.8+ KB

In [52]:
da_hint=pd.read_csv("./icr-identify-age-related-conditions/greeks.csv")

In [53]:
da_hint=da_hint[da_hint["Alpha"]!="A"]

In [54]:
da_hint

               Id Alpha Beta Gamma Delta     Epsilon
0    000ff2bfdfe9     B    C     G     D   3/19/2019
4    044fb8a146ec     D    B     F     B   3/25/2020
10   06055f3f6785     D    B     F     B   6/23/2020
13   06c0ddf265c5     D    B     E     B   9/27/2019
31   0e798fd4e6e7     D    B     E     A   7/24/2020
..            ...   ...  ...   ...   ...         ...
576  ed3486389307     G    C     B     C  12/10/2018
585  f16b095a433f     G    C     B     C  12/10/2018
588  f26ee0cee841     B    B     H     A  11/12/2019
592  f405c0b5836f     B    C     H     C   2/13/2019
608  fbb79ba9d642     B    C     H     B   4/17/2019

[108 rows x 6 columns]

In [55]:
da_hint= da_hint.drop(["Delta","Gamma","Beta","Epsilon"],axis=1)

In [56]:
da_hint

new_data=da_hint.merge(da_no1)

In [58]:
new_data
new_data.to_csv("./icr-identify-age-related-conditions/sample_data/maybe_datq.csv")

In [72]:
da2=da1.iloc[:,50:]

In [73]:
da2.describe()

,FS,GB,GE,GF,GH,GI,GL,Class
count,615.000000,617.000000,617.000000,617.000000,617.000000,617.000000,616.000000,617.000000
mean,0.421501,20.724856,131.714987,14679.595398,31.489716,50.584437,8.530961,0.175041
std,1.305365,9.991907,144.181524,19352.959387,9.864239,36.266251,10.327010,0.380310
min,0.067730,4.102182,72.611063,13.038894,9.432735,0.897628,0.001129,0.000000
25%,0.067730,14.036718,72.611063,2798.992584,25.034888,23.011684,0.124392,0.000000
50%,0.250601,18.771436,72.611063,7838.273610,30.608946,41.007968,0.337827,0.000000
75%,0.535067,25.608406,127.591671,19035.709240,36.863947,67.931664,21.978000,0.000000
max,31.365763,135.781294,1497.351958,143790.071200,81.210825,191.194764,21.978000,1.000000